name: If merged (all branchies)

on:
  pull_request:
    branches: 
      - '*'
    types:
      - closed  

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
